### ISSUE TITLE
Domain name + HTTPS challenge

### ISSUE THREAD

**Issue by peanut11** [kfwong/cs3226-lab#40]
(EASY WITH "LetsEncrypt" BUT A BIT COSTLY FOR GOOD DOMAIN NAME): If your capstone project group is still using IP address as of Lab5, try to get a free (but usually meaningless) domain name. Once you have a domain name for your DO droplet, setup HTTPS using LetsEncrypt. However, if your capstone project group already have a very strong idea on what to do for capstone project and already decide on the name for the capstone project, then immediately buy a meaningful+short domain name using NameCheap, GoDaddy, Exabytes (for .sg domain) before it is taken by others and use it to claim this achievement for this Lab6. Your capstone project group will have to do this by Week 13 anyway.

**Comment by kfwong** [comment]
Github Education pack has free domain (.me TLD) & SSL for free. However someone might have to contribute his/her credit to choose a "relavant" domain name.

Alternatively, if all of us are willing to fork out $$$ to buy a domain name, I can help maintaining it on NameCheap. (SAY NO to GoDaddy! The user interface suck ball and slow)

**Comment by kfwong** [comment]
Fixed.
