### ISSUE TITLE
Internalization + localization challenge

### ISSUE THREAD

**Issue by peanut11** [kfwong/cs3226-lab#42]
(EASIER if your group has members who can speak various languages): If you (or your project group members) know any other language other than English, translate all the English text in your application to at least one other language, then give option for your user to switch language (and maybe also record his/her language preference in the users table database). You can do this on client-side version (use JavaScript to change the html text of your paragraphs or span elements — not the best way to do this) or server-side version (use PHP to switch between languages — the better way). We will discuss this topic more in future class but you are free to use any simple strategy that works, including this.

**Comment by kfwong** [comment]
#51 FIxed
