### ISSUE TITLE
Social media challenge

### ISSUE THREAD

**Issue by peanut11** [kfwong/cs3226-lab#44]
(CAN BE HARD for those who have not tried this before): Do a self-study on Facebook Developers Page to add Facebook like button in your HTML files. Test it by clicking like and seeing it appears in your own Facebook account newsfeed. If you can already do that, also try Twitter tweet button.

**Comment by kfwong** [comment]
Random Suggestion.
- Like/Share Button
- Allow Login via Facebook

**Comment by pianonerd7** [comment]
564be47e15eaff163c275394a504ebfa7574fba7
