### ISSUE TITLE
On accessing unavailable routes (HTTP error 404), or any other non HTTP 200 responses, give a more graceful error message than Laravel default

### ISSUE THREAD

**Issue by pianonerd7** [kfwong/cs3226-lab#7]
https://www.amazon.com/thispagedoesnotexist

**Comment by pianonerd7** [comment]
ac9b7863eb026213e6dad72d058c48c410de55fd

**Comment by kfwong** [comment]
Tested but the error handling is displaying a blank page on my local dev machine.

**Comment by kfwong** [comment]
The server return a 500 Internal Server error instead of 404 if page is not found.
![2017-02-21--1487672473_1920x1080_scrot](https://cloud.githubusercontent.com/assets/3982414/23160765/a9f473aa-f862-11e6-9106-69c2e62112b0.png)

**Comment by kfwong** [comment]
Fixed by PR #33
