### ISSUE TITLE
the fun one *wink*wink*

### ISSUE THREAD

**Issue by pianonerd7** [kfwong/cs3226-lab#8]
Back in Lab3, we have:
Set the row height of row i+1 according to the difference of column Sum values between row i and row i+1. That is, the bigger the gap, the bigger the visual gap has to be (you are free to calibrate the gap rules as long as it is visually consistent). However, turn off this feature when user clicks on a column header as the sort order will likely be different. This likely requires some custom JS coding work.
Now use this rule:
Set the row height of row i+1 according to the difference of the active sort column values between row i and row i+1. That is, the bigger the gap, the bigger the visual gap has to be (although you are still free to calibrate the gap rules as long as it is visually consistent, you should minimize vertical scrolling, i.e. don't use too much whitespace). of course, only apply this row height feature when the active sort column contains numbers.

**Comment by kfwong** [comment]
PR #28 mark resolved.
